version: "3.3"
services:
    web:
        build: 
            context: ./kebera
            dockerfile: Dockerfile
        image: php:7.4-apache
        container_name: php74
        ports: 
            - "8001:80"
        volumes:
            - ./kebera:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        container_name: mysql8
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: KeBERA
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8999:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: